name: Docker image CI

on:
  push:
    branches:
      - 'metadata-indicators'
  pull_request:
    branches:
      - 'metadata-indicators'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: 'geocat/gn4-inspire-geoportal'

jobs:
  docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to GHCR
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Transform GitHub Actions metadata to Docker image tags
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: '{{ env.REGISTRY }}/{{ env.IMAGE_NAME }}'
          labels: |
            org.opencontainers.image.vendor=GeoCat B.V.
          flavor: |
            latest=auto
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern={{major}},enable=${{ !startsWith(github.ref, 'refs/tags/v0.') }}
            type=raw,,value={{branch}}-{{sha}}
      -
        name: Build image
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./docker/geocat/DockerfileGeocat
          platforms: linux/amd64,linux/arm64
          build-args: |
            "DATA_DIR=/usr/local/live-geonetwork/data"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

    
